services:
  api:
    container_name: "runner"
    build:
      context: .
      dockerfile: Dockerfile.multi
    environment:
      - FORMATTER_URL=http://formatter:8080
    networks:
      - reverse-proxy-network

spring:
  redis:
    host: redis
    port: 6379

networks:
  reverse-proxy-network:
    external: true