services:
  runner:
    container_name: "app-runner"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "19083:8080"
    environment:
      DB_USER: app
      DB_PASSWORD: app
      DB_NAME: snippet-db
      DB_HOST: runner-db
      DB_PORT: 5432
      BUCKET_SERVICE: host.docker.internal
      BUCKET_PORT: 1992
      REDIS_HOST: host.docker.internal
      REDIS_PORT: 6379
      APP_HOST: host.docker.internal
      APP_PORT: 19081
    depends_on:
      - runner-db

  runner-db:
    container_name: "runner-db"
    image: postgres:16
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: snippet-db
    volumes:
      - runner-pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

volumes:
  runner-pgdata: