services:
  main-app:
    container_name: "app"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_USER: app
      DB_PASSWORD: app
      DB_NAME: snippet-db
      DB_HOST: db
      DB_PORT: 5432
    networks:
      - snippetsearcher-network    # acceso interno
      - reverse-proxy-network      # expuesto al p√∫blico

  db:
    container_name: snippet-db
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: snippet-db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - snippetsearcher-network

volumes:
  pgdata:

networks:
  snippetsearcher-network:
    external: true
  reverse-proxy-network:
    external: true
