services:
  api:
    container_name: "runner"
    build:
      context: .
      dockerfile: Dockerfile.multi
    environment:
      - SNIPPET_SERVICE_URL=http://app:8080
      - FORMATTER_URL=http://formatter:8080
    networks:
      - reverse-proxy-network

networks:
  reverse-proxy-network:
    external: true