services:
  main-app:
    container_name: "app"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    environment:
      DB_USER: app
      DB_PASSWORD: app
      DB_NAME: snippet-db
      DB_HOST: localhost
      DB_PORT: 5434
      BUCKET_HOST: localhost
      BUCKET_PORT: 8080
      REDIS_HOST: localhost
      REDIS_PORT: 6379
    depends_on:
      - runner-db

  runner-db:
    container_name: "runner-db"
    image: postgres:16
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: snippet-db
    volumes:
      - runner-pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

volumes:
  runner-pgdata: