spring:
  application:
    name: snippet-searcher-runner
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 2000
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

redis:
  stream:
    key: "jobs"

app:
  bucket:
    url: http://${BUCKET_SERVICE}:${BUCKET_PORT}
  app:
    url: http://${APP_HOST}:${APP_PORT}

server:
  port: 8080

logging:
  pattern:
    console: "[%X{request_id}] %d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  level:
    root: INFO
    com.grupo14IngSis.snippetSearcher: DEBUG