spring:
  application:
    name: snippet-searcher-runner
  data:
    redis:
      host: redis
      port: 6379
redis:
  stream:
    key: "jobs"

app:
  bucket:
    url: http://${BUCKET_SERVICE}:${BUCKET_PORT}
  app:
    url: http://${APP_HOST}:${APP_PORT}


server:
  port: 8082

# Configuraci√≥n de logs con request-id
logging:
  pattern:
    console: "[%X{request_id}] %d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  level:
    root: INFO
    com.grupo14IngSis.snippetSearcher: DEBUG
#jwt:
#  secret: tu-super-secreto-jwt-key-minimo-256-bits
#  expiration: 86400000 # 24 horas en ms


